backend:
  name: git-gateway
  branch: master

media_folder: "public/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "info" # Used in routes, e.g., /admin/collections/blog
    label: "Info" # Used in the UI
    folder: "_data/info" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Peso", name: "weight", widget: "number" }
      - { label: "Lunghezza", name: "length", widget: "number" }
      - { label: "Data", name: "date", widget: "datetime" }
